// Exportando componentes de partes da página Home
export { default as Header } from './header';
export { default as Hero } from './hero';
export { default as ProductService } from './product-service';
export { default as Card } from './card';
export { default as Section } from './section';
export { default as Comments } from './comments';
export { default as Invite } from './invite';
export { default as Questions } from './questions';
export { default as Footer } from './footer';